menuscreen/event/routes.py
from flask import(render_template, url_for, flash, redirect,
                    request, abort, jsonify, Blueprint)
from datetime import datetime
from flask_login import current_user, login_required
from menuscreen import db
from menuscreen.models import User, Event
from menuscreen.event.forms import EventForm
from menuscreen.event.utils import getTime, _getEvents, _getEventsSortAsc
from menuscreen.users.init_db_tables import getVenueId

event = Blueprint('event', __name__)


@event.route('/_get_event_current_list', methods=['GET', 'POST'])
# @login_required
def _get_event_current_list():
    data = request.get_json()
    print("**************************************")
    print("**************************************")
    print("list_history. /_get_event_current_list")
    print(data)
    if (current_user.is_authenticated):
        print("LOGGED IN")
        print(current_user.id)

        data['userId'] = current_user.id
        print("data: {}".format(data))
        data = _getEventsSortAsc(data)

    elif (data):
        print("NOT LOGGED IN")
        current_user_id = getVenueId(data['userName'])
        print(current_user_id)
        data['userId'] = current_user_id
        print("data: {}".format(data))
        data = _getEventsSortAsc(data)
    else:
        print("NOT LOGGED IN AND NO URL INFO")
        data = {}
    print("**************************************")
    print("**************************************")
    return jsonify(data)

@event.route('/event_dashboard', methods=['GET', 'POST'])
@login_required
def event_dashboard():
    events = [
        {
            "id":1,
            "artist":"eventArtist",
            "name":"eventName",
            "date_of_event":"eventDOE",
            "starttime_of_event":"eventSTOE",
            "endtime_of_event":"eventETOE",
            "location":"eventLocation",
        }
    ]
    events = _getEvents(current_user.id)
    # events = Event.query.filter_by(venue_db_id=current_user.id).all()
    return render_template('event_dashboard.html', title="Event Dashboard", legend='Event Dashboard', events=events)

@event.route('/add_event', methods=['GET', 'POST'])
@login_required
def add_event():
    form = EventForm(request.form)
    if request.method == 'POST':
        event = {
            "eventName":request.form['eventname'],
            "eventArtist":request.form['eventartist'],
            "eventDate":request.form['eventdate'],
            "eventStartTime":request.form['eventstarttime'],
            "eventEndTime":request.form['eventendtime'],
            "eventLocation":request.form['eventlocation'],
        }
        event = Event(
            name=event['eventName'],
            artist=event['eventArtist'],
            date_of_event=event['eventDate'],
            starttime_of_event=event['eventStartTime'],
            endtime_of_event=event['eventEndTime'],
            location=event['eventLocation'],
            venue_db_id=current_user.id
        )
        db.session.add(event)
        db.session.commit()
        flash('Event created', 'success')
        return redirect(url_for('event.event_dashboard'))
    return render_template('add_event.html', title="Add Event", legend='Add Event', form=form)

@event.route('/edit_event/<string:id>', methods=['GET', 'POST'])
@login_required
def edit_event(id):
    # event = Event.query.filter_by(id=id, venue_db_id=current_user.id).first()
    event = Event.query.get_or_404(id)
    if event.venue_db_id != current_user.id:
        abort(403)# Get form
    form = EventForm(request.form)
    # Populate event form fields
    form.eventName.data = event.name
    form.eventArtist.data = event.artist
    form.eventDate.data = event.date_of_event
    form.eventStartTime.data = getTime(event.starttime_of_event)
    form.eventEndTime.data = getTime(event.endtime_of_event)
    form.eventLocation.data = event.location
    print('event: {}'.format(event))

    if request.method == 'POST':
        newEvent = {
            "name" : request.form['eventname'],
            "artist" : request.form['eventartist'],
            "date" : request.form['eventdate'],
            "startTime" : request.form['eventstarttime'],
            "endTime" : request.form['eventendtime'],
            "location" : request.form['eventlocation'],
        }
        event.name = newEvent['name']
        event.artist = newEvent['artist']
        event.date_of_event =  newEvent['date']
        event.starttime_of_event =  newEvent['startTime']
        event.endtime_of_event =  newEvent['endTime']
        event.location =  newEvent['location']
        db.session.commit()
        flash('Event changed!', 'success')
        return redirect(url_for('event.event_dashboard'))
    return render_template('edit_event.html', title="Edit Event", legend='Edit Event', form=form, event=event)

@event.route('/delete_event/<string:id>', methods=['POST'])
@login_required
def delete_event(id):
    # event = Event.query.filter_by(id=id, venue_db_id=current_user.id).first()
    event = Event.query.get_or_404(id)
    if event.venue_db_id != current_user.id:
        abort(403)
    db.session.delete(event)
    db.session.commit()
    flash('Event Deleted!', 'success')
    return redirect(url_for('event.event_dashboard'))

menuscreen/main/routes.py
from flask import render_template, request, Response, Blueprint
from flask_login import current_user, login_required
from menuscreen import db
from menuscreen.models import User, List_history, List_current


main = Blueprint('main', __name__)

@main.route('/')
def index():
    # return render_template('index.html', title='Index', current_user=current_user)
    return render_template('home.html', title='Index', current_user=current_user)

@main.route('/home')
def home():
    return render_template('home.html', title='Home', current_user=current_user)

menuscreen/wine/routes.py
from flask import (render_template, url_for, flash, redirect,
                    request, abort, json, jsonify, Blueprint)
from flask_login import current_user, login_required
from menuscreen import db
from menuscreen.models import User, Wine, Winelist_current, Wine_type
from menuscreen.wine.forms import WineForm, CurrentWinelistForm, WineTypeForm
from menuscreen.wine.utils import getDefaultCurrentWinelist, _getWinelistDisplay, _getWine, _getWinetypes, _convertToWinelist
from menuscreen.users.init_db_tables import getVenueId

from menuscreen import pusher_client

wine = Blueprint('wine', __name__)

# Get all wines from db
@wine.route('/_getwines', methods=['GET','POST'])
@login_required
def _getwines():
    user = User.query.filter_by(id=current_user.id).first()
    datas = user.winelist_sort_asc
    wines = []
    for data in datas:
        wine = {
            "id":data.id,
            "name":data.name,
            "varietal":data.varietal,
            "type":data.type,
            "location":data.location,
            "glass":data.glass,
            "bottle":data.bottle,
            "description":data.description,
            "food_pairings":data.food_pairings,
            "website":data.website,
        }
        wines.append(wine)
    return jsonify(wines)


# Get current all wines from db
@wine.route('/_getCurrentWinelist', methods=['GET','POST'])
@login_required
def _getCurrentWinelist():
    # user = User.query.filter_by(id=current_user.id).first()
    # result = cur.execute("SELECT wl.name, wl.location, wl.description, wl.glass, wl.bottle, wl.varietal, wl.food_pairings FROM winelist_current AS wc, wines AS wl WHERE wl.id=wc.id_wine AND wl.venue_db_id=wc.venue_db_id AND wc.venue_db_id=%s", [venuedbid])

    user = User.query.filter_by(id=current_user.id).first()
    data = user.winelist_current
    data = db.session.query(
        Wine.name,
        Wine.location,
        Wine.description,
        Wine.glass,
        Wine.bottle,
        Wine.varietal,
        Wine.food_pairings,
        Wine.website,
        Winelist_current.id_dropdown
        ).outerjoin(Winelist_current, Wine.id == Winelist_current.id_wine
        ).filter(Winelist_current.venue_db_id == current_user.id
        ).order_by(Winelist_current.id_dropdown.asc()
        ).all()

    return jsonify(data)

# Add wine type
@wine.route('/add_wine_type', methods=['GET', 'POST'])
@login_required
def add_wine_type():
    form = WineTypeForm(request.form)
    rdata = _getWinetypes(current_user.id)
    wineTypes = _convertToWinelist(rdata)

    form.wineTypeSelect.choices = [(wineType['id'], wineType['type']) for wineType in wineTypes]
    if form.validate_on_submit():
        reqData = request.form['wineType']
        wineType = Wine_type(type=reqData, venue_db_id=current_user.id)
        db.session.add(wineType)
        db.session.commit()
        return redirect(url_for('wine.add_wine_type'))

    return render_template('add_wine_type.html', title='Edit Wine Type', legend='Edit Wine Type', form=form)


# Add Wine
@wine.route('/add_wine', methods=['GET', 'POST'])
@login_required
def add_wine():
    form = WineForm(request.form)

    user = User.query.filter_by(id=current_user.id).first()
    datas = db.session.query(
        Wine_type.id,
        Wine_type.type,
        ).filter(Wine_type.venue_db_id == current_user.id
        ).order_by(Wine_type.type.asc()
        ).all()
    print(datas)
    typelist = []
    for data in datas:
        type = {
            "id" : data.id,
            "type" : data.type
        }
        typelist.append(type)

    types = typelist

    form.type.choices = [(type['id'], type['type']) for type in types]

    if request.method == 'POST' and form.validate():
        # SQLAlchemy to add to database
        wine = Wine(name=form.name.data,
            location=form.location.data,
            varietal=form.varietal.data,
            type=form.type.data,
            glass=form.glass.data,
            bottle=form.bottle.data,
            description=form.description.data,
            food_pairings=form.food_pairings.data,
            website=form.website.data,
            venue_db_id=current_user.id)
        db.session.add(wine)
        db.session.commit()

        settings = {
            "venue_db_id": current_user.id,
            "updated": True,
        }
        #######################################
        #PUSHER
        pusher_client.trigger('wine-event-channel', 'add-wine-event', {'message': settings})
        #PUSHER
        #######################################

        flash('Wine Created', 'success')
        return redirect(url_for('wine.wine_dashboard'))
    return render_template('add_wine.html', title='Add Wine', legend='Add Wine', form=form)

# Wine menu
@wine.route('/wine_dashboard', methods=['GET', 'POST'])
@login_required
def wine_dashboard():
    # wines = Wine.query.all()
    user = User.query.filter_by(id=current_user.id).first()
    wines = user.winelist_sort_asc
    for wine in wines:
        wine.dash_menu_id = list(wine.name)[0].lower()
    if wines:
        return render_template('wine_dashboard.html', title='Wine Dashboard', wines=wines, currentUserId=current_user.id)
    else:
        msg = 'Sorry, sad day. No wine found in your winelist!'
    return render_template('wine_dashboard.html', title='Wine Dashboard', legend='Wine Dashboard', msg=msg, currentUserId=current_user.id)

# Edit wine
@wine.route('/edit_wine/<string:wine_id>', methods=['GET', 'POST'])
@login_required
def edit_wine(wine_id):
    wine = Wine.query.get_or_404(wine_id)
    if wine.venue_db_id != current_user.id:
        abort(403)
    # Get form
    form = WineForm(request.form,
        type = wine.type
    )

    rdata = _getWinetypes(current_user.id)
    wineTypes = _convertToWinelist(rdata)
    form.type.choices = [(type['id'], type['type']) for type in wineTypes]

    if form.validate_on_submit():
    # if request.method == 'POST':
        wine.name = form.name.data
        wine.location = form.location.data
        wine.varietal = form.varietal.data
        wine.type = form.type.data
        wine.glass = form.glass.data
        wine.bottle = form.bottle.data
        wine.description = form.description.data
        wine.food_pairings = form.food_pairings.data
        wine.website = form.website.data
        db.session.add(wine)
        db.session.commit()

        settings = {
            "venue_db_id": current_user.id,
            "updated": True,
        }

        #######################################
        #PUSHER
        pusher_client.trigger('wine-event-channel', 'edit-wine-event', {'message': settings})
        #PUSHER
        #######################################

        flash('Wine Updated!!!', 'success')
        return redirect(url_for('wine.wine_dashboard'))

    elif request.method == 'GET':
        rdata = _getWinetypes(current_user.id)
        wineTypes = _convertToWinelist(rdata)
        # # print(wineTypes)
        # for x in wineTypes:
        #     print("x['type']: {}".format(x['type']))
        #
        # print("wine.type: {}".format(wine.type))

        # Populate wine form fields
        # Populate the type select with values from the DB
        form.type.data = wine.type
        form.type.choices = [(type['id'], type['type']) for type in wineTypes]
        form.name.data = wine.name
        form.location.data = wine.location
        form.varietal.data = wine.varietal
        form.glass.data = wine.glass
        form.bottle.data = wine.bottle
        form.description.data = wine.description
        form.food_pairings.data = wine.food_pairings
        form.website.data = wine.website

    return render_template('edit_wine.html', title='Edit Wine', legend='Edit Wine', form=form)

# Delete wine
@wine.route('/delete_wine/<string:wine_id>', methods=['POST'])
@login_required
def delete_wine(wine_id):

    wine = Wine.query.get_or_404(wine_id)
    if wine.venue_db_id != current_user.id:
        abort(403)
    db.session.delete(wine)
    db.session.commit()

    # Flash message
    flash('Wine Deleted!!!', 'success')
    return redirect(url_for('wine.wine_dashboard'))


# Winelist editor
@wine.route('/winelist_editor', methods=['GET','POST'])
@login_required
def winelist_editor():

    user = User.query.filter_by(id=current_user.id).first()
    datas = user.winelist_sort_asc
    wines = []
    for data in datas:
        wine = {
            "id":data.id,
            "name":data.name,
            "varietal":data.varietal,
            "location":data.location,
            "glass":data.glass,
            "bottle":data.bottle,
            "description":data.description,
            "food_pairings":data.food_pairings,
            "website":data.website,
        }
        wines.append(wine)

    wine1select = getDefaultCurrentWinelist('1')
    wine2select = getDefaultCurrentWinelist('2')
    wine3select = getDefaultCurrentWinelist('3')
    wine4select = getDefaultCurrentWinelist('4')
    wine5select = getDefaultCurrentWinelist('5')
    wine6select = getDefaultCurrentWinelist('6')
    wine7select = getDefaultCurrentWinelist('7')
    wine8select = getDefaultCurrentWinelist('8')
    wine9select = getDefaultCurrentWinelist('9')
    wine10select = getDefaultCurrentWinelist('10')
    wine11select = getDefaultCurrentWinelist('11')
    wine12select = getDefaultCurrentWinelist('12')
    wine13select = getDefaultCurrentWinelist('13')
    wine14select = getDefaultCurrentWinelist('14')
    wine15select = getDefaultCurrentWinelist('15')
    wine16select = getDefaultCurrentWinelist('16')
    wine17select = getDefaultCurrentWinelist('17')
    wine18select = getDefaultCurrentWinelist('18')
    wine19select = getDefaultCurrentWinelist('19')
    wine20select = getDefaultCurrentWinelist('20')
    wine21select = getDefaultCurrentWinelist('21')
    wine22select = getDefaultCurrentWinelist('22')
    wine23select = getDefaultCurrentWinelist('23')
    wine24select = getDefaultCurrentWinelist('24')

menuscreen/templates/includes/_beernav_btns.html
<a class="btn btn-success" href="/add_beer"> Add Beer</a>
<a class="btn btn-success" href="/beersearch">Search Beers</a>
<a class="btn btn-danger" href="/edit_beer_list">Beerlist Editor</a>
<a class="btn btn-danger" href="/beer_dashboard">Beer Dashboard</a>
<a class="btn btn-danger" href="/on_tap_next_editor">On Tap Next Editor</a>

menuscreen/templates/includes/_formhelpers.html
{% macro render_field(field) %}
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
      <span class="help-inline">{{ error }}</span>
    {% endfor %}
  {% endif %}
{% endmacro %}

menuscreen/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}


{% if error %}
  <div class="alert alert-danger">{{error}}</div>
{% endif %}

{% if msg %}
  <div class="alert alert-success">{{msg}}</div> 
{% endif %}

menuscreen/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="{{ url_for('main.index') }}">Bar Menu</a> -->
  <a class="navbar-brand" href="{{ url_for('main.home') }}">Bar Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <!-- <li class="nav-item">
        <a class="nav-link" href="{{ url_for('displays.draft_beers_print') }}">Print</a>
      </li> -->

      <!-- <li class="nav-item">
        <a class="nav-link" href="{{ url_for('displays.beers_display_screen') }}">Beers On Screen</a>
      </li> -->

      <!-- <li class="nav-item">
        <a class="nav-link" href="{{ url_for('displays.on_tap_next_display') }}">On Tap Next</a>
      </li> -->

      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tablet Screen
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ url_for('displays.draft_beers') }}">Draft Beer List</a>
            <a class="dropdown-item" href="{{ url_for('displays.bottle_beers') }}">Bottle Beer List</a>
            <a class="dropdown-item" href="{{ url_for('wine.winelist_menu') }}">Wine Menu</a>
            <a class="dropdown-item" href="{{ url_for('wine.winelist_description') }}">Wine Descriptions</a>
        </div>
      </li> -->

      {% if current_user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Beer
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('list_history.beer_dashboard') }}">Beer Dashboard</a>
              <a class="dropdown-item" href="{{ url_for('list_history.edit_beer_list') }}">Beerlist Editor</a>
              <a class="dropdown-item" href="{{ url_for('list_history.beersearch') }}">Search Beer to add</a>
              <a class="dropdown-item" href="{{ url_for('list_history.add_beer') }}">Add Beer Manually</a>
              <!-- <a class="dropdown-item" href="{{ url_for('displays.draft_beers_print') }}">Beer List</a>
              <a class="dropdown-item" href="{{ url_for('list_history.on_tap_next_editor') }}">On Tap Next Editor</a> -->
          </div>
        </li>

        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Images
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('image.image_dashboard') }}">Image Dashboard</a>
              <a class="dropdown-item" href="{{ url_for('image.add_image') }}">Add Image</a>
          </div>
        </li> -->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Wine
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('wine.wine_dashboard') }}">Wine Dashboard</a>
              <!-- <a class="dropdown-item" href="{{ url_for('wine.winelist_editor') }}">Winelist Editor</a> -->
              <a class="dropdown-item" href="{{ url_for('wine.winelist_menu') }}">Wine List</a>
          </div>
        </li>

        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Events
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('event.event_dashboard') }}">Event Dashboard</a>
              <a class="dropdown-item" href="{{ url_for('event.add_event') }}">Add Event</a>
          </div>
        </li> -->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Settings
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('settttings.beerscreen_settings') }}">Beerscreen Settings</a>
              <!-- <a class="dropdown-item" href="{{ url_for('settttings.add_font_size') }}">Add Font Size options</a> -->
              <!-- <a class="dropdown-item" href="{{ url_for('settttings.add_template') }}">Add Template</a> -->
              <a class="dropdown-item" href="{{ url_for('settttings.edit_drink_size') }}">Edit Drink Sizes</a>
              <a class="dropdown-item" href="{{ url_for('settttings.edit_drink_price') }}">Edit Drink Prices</a>
              <a class="dropdown-item" href="{{ url_for('wine.add_wine_type') }}">Add Wine Type</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
        </li>
      {% endif %}

    </ul>
  </div>
</nav>

menuscreen/templates/includes/_subnavbar.html
<!-- <nav class="navbar navbar-expand-lg navbar-light">
  <div class="" id="navbarNav">
    <ul id="subnavbar" class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/draft_beers">Draft Beers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/bottle_beers">Bottle Beers</a>
      </li>
    </ul>
  </div>
</nav> -->


<!-- <div class="col-12 mx-auto">
  <div class="row mb-3 justify-content-center">
    <div class="d-inline nav-item ">
      <a class="d-inline nav-link btn btn-success" href="/draft_beers">Draft Beers</a>
      <a class="d-inline nav-link btn btn-success" href="/bottle_beers">Bottle Beers</a>
    </div>
  </div>
  <div class="row mb-3 justify-content-center">
    <div class="d-inline nav-item ">
      <a class="d-inline nav-link btn btn-success" href="/winelist_menu">Wine Menu</a>
      <a class="d-inline nav-link btn btn-success" href="/winelist_description">Wine Descriptions</a>
    </div>
  </div>
</div> -->

<!-- <div class="mx-auto">
  <div class="d-flex flex-wrap justify-content-around">
    <div class="d-flex flex-wrap justify-content-around">

      <div class="mt-2 mx-2">
        <a class=" nav-link btn btn-outline-success" href="{{ url_for('displays.draft_beers') }}">Draft Beers</a>
      </div>
      <div class="mt-2 mx-2">
        <a class=" nav-link btn btn-outline-success" href="{{ url_for('displays.bottle_beers') }}">Bottle Beers</a>
      </div>

    </div>
    <div class="d-flex flex-wrap justify-content-around">

      <div class="mt-2 mx-2">
        <a class=" nav-link btn btn-outline-success" href="{{ url_for('wine.winelist_menu') }}">Wine Menu</a>
      </div>
      <div class="mt-2 mx-2">
        <a class=" nav-link btn btn-outline-success" href="{{ url_for('wine.winelist_description') }}">Wine Descriptions</a>
      </div>

    </div>
  </div>
</div> -->

<div class="mx-auto">
  <div class="d-flex flex-wrap justify-content-around">
    <div class="d-flex flex-wrap justify-content-around">

      <div class="mt-2 mx-2">
        <div id="website-back-btn" class="btn btn-sm btn-outline-success">Back</div>
      </div>
      <div class="mt-2 mx-2">
        <!-- <input class="nav-link btn btn-outline-success" href="{{ url_for('displays.draft_beers') }}">Draft Beers</a> -->
        <!-- <input id="draft-beers-tablet" class=" btn btn-sm btn-outline-success" type="click" value="Draft Beers"> -->
        <div id="draft-beers-tablet" class="btn btn-sm btn-outline-success">Draft Beers</div>
      </div>
      <div class="mt-2 mx-2">
        <!-- <input id="bottle-beers-tablet" class="btn btn-sm btn-outline-success" type="click" value="Bottle Beers"> -->
        <div id="bottle-beers-tablet" class="tablet btn btn-sm btn-outline-success">Bottle Beers</div>
      </div>

    </div>
    <div class="d-flex flex-wrap justify-content-around">

      <div class="mt-2 mx-2">
        <!-- <input id="winelist-menu-tablet" class="nav-link btn btn-sm btn-outline-success" type="click" value="Wine Menu"> -->
        <div id="winelist-menu-tablet" class="btn btn-sm btn-outline-success">Wine Menu</div>
      </div>
      <div class="mt-2 mx-2">
        <!-- <input id="winelist-description-tablet" class="nav-link btn btn-sm btn-outline-success" type="click" value="Wine Description"> -->
        <div id="winelist-description-tablet" class="btn btn-sm btn-outline-success">Wine Description</div>
      </div>

    </div>
  </div>
</div>

<!-- <div class="mx-auto">
  <div class="d-inline nav-item ">
    <a class="d-inline nav-link btn btn-success" href="/draft_beers">Draft Beers</a>
    <a class="d-inline nav-link btn btn-success" href="/bottle_beers">Bottle Beers</a>
    <a class="d-inline nav-link btn btn-success" href="/winelist_menu">Wine Menu</a>
    <a class="d-inline nav-link btn btn-success" href="/winelist_description">Wine Descriptions</a>
  </div>
</div> -->